Repository SethClydesdale/genki-study-resources, pull requests merged in 2020-12, with the labels that each got.

#114 Fix for lesson 8 grammar 8
  lessons-3rd/lesson-8/grammar-8/index.html
Labels: incorrect answer

#115 Fix missing index on lessons-3d lesson-6 grammar-3
  lessons-3rd/lesson-6/grammar-3/index.html
Labels: suggestion

#116 Fix typo in lesson 9 grammar 2
  lessons-3rd/lesson-9/grammar-2/index.html
Labels: typo
