Repository SethClydesdale/genki-study-resources, pull requests merged in 2023-02, with the labels that each got.

#191 start or pause timer according to page visibility
  resources/javascript/genki.js
  resources/javascript/genki.min.js
  resources/javascript/head.js
  resources/javascript/head.min.js
Labels: enhancement

#194 Fix typo, 行く should be いく and not いき (L6 vocab 5)
  lessons/lesson-6/vocab-5/index.html
Labels: typo

#197 Add missing word to Lesson 11 - Workbook 5
  lessons-3rd/lesson-11/workbook-5/index.html
  lessons/lesson-11/workbook-5/index.html
Labels: improvement
