Repository SethClydesdale/genki-study-resources, pull requests merged in 2023-12, with the labels that each got.

#229 Save results in local storage
  .gitignore
  resources/css/stylesheet.css
  resources/css/stylesheet.min.css
  resources/javascript/genki.js
  resources/javascript/genki.min.js
Labels: enhancement

#228 Fix incorrect verb stem in Lesson 18 Reading Practice
  lessons-3rd/lesson-18/literacy-11/index.html
Labels: typo

#230 fixed overall score for drag and drop
  resources/javascript/genki.js
  resources/javascript/genki.min.js
Labels: bug, improvement

#235 Allow 鍵 in place of かぎ.
  lessons/lesson-17/workbook-5/index.html
Labels: improvement
